### ISSUE TITLE
Real-time push Notifications

### ISSUE THREAD

**Issue by myhubacct** [ShihabM/Mast#9]
Thanks for these nice app. 

There seems to be an issue with the real-time push notifications setting, it doesn’t functioning at all. I don’t get any notification about new mentions, likes or boosts. 

iPhone 6
iOS 12.1
Mast 1.2.4

**Comment by dar-irl** [comment]
Same issue here, I'm not getting any push notifications.

**Comment by SomniusTiger** [comment]
I'm also experiencing this! I'm unsure, but I wonder if it's an instance configuration issue instead of an app-issue.

I'm unsure if this information will help, but my instance, https://merveilles.town, uses Amazon S3 for image hosting. I'm also using Mastodon v2.6.5.

If needed, I'm available to help debug this issue!

**Comment by myhubacct** [comment]
Have reinstalled completely the app afterwards it seems to work as expected. For now I would say it’s solved for me. 

Environment
iPhone 6
iOS 12.4
Mast 1.7.6
